books/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.views.static import serve

app_name = 'books'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^categories/$', views.category_list, name='category_list'),
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)$', views.show_category, name='show_category'),
    url(r'^book/(?P<id>[\d]+)$', views.show_book, name='show_book'),
    url(r'^book/(?P<id>[\d]+)/edit/$', views.edit_book, name='edit_book'),
    url(r'^book/(?P<id>[\d]+)/download/$', views.download, name='download'),
    url(r'^book/(?P<id>[\d]+)/add_tag/$', views.add_tag, name='add_tag'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_book/$', views.add_book, name='add_book'),
    url(r'^like/$', views.like_book, name='like_book'),
    url(r'^search/', views.search, name='search'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }, name='serve'),
    ]

my_library/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('books.urls')),
]

books/models.py
import os.path
from datetime import datetime

from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


def category_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/category/<filename>
    return '{0}/{1}'.format(instance.category.slug, filename)


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

        permissions = (
            ("can_add", "Can add new category."),
        )

    def __str__(self):
        return self.name


class Tag(models.Model):
    tag = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.tag


class Book(models.Model):
    category = models.ForeignKey(Category)
    tag = models.ManyToManyField(Tag)

    title = models.CharField(max_length=128)
    author = models.CharField(max_length=32)
    publisher = models.CharField(max_length=32, blank=True)
    published_date = models.DateField(null=True)
    short_description = models.TextField(blank=True)
    related_url = models.URLField(blank=True)

    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    downloads = models.IntegerField(default=0)

    upload = models.FileField(upload_to=category_path, blank=True)
    date_uploaded = models.DateTimeField(editable=False)
    date_modified = models.DateTimeField()

    class Meta:
        permissions = (
            ("can_edit", "Can edit the book."),
        )

    def save(self, *args, **kwargs):
        if not self.id:
            self.date_uploaded = timezone.now()
        self.date_modified = timezone.now()
        return super(Book, self).save(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.upload.name)

    def is_recent(self):
        if (timezone.now() - self.date_uploaded).days < 1:
            return True
        else:
            return False

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from books.models import Category, Book, Tag


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class BookForm(forms.ModelForm):

    title = forms.CharField(label='Title:', max_length=128,
                            help_text="Please enter the title of the book.")
    author = forms.CharField(label='Author:', max_length=32,
                             help_text="Please enter the author of the book, "
                                       "if there are more than one, "
                                       "plese use comma to seprate.")
    publisher = forms.CharField(label='Publisher:', max_length=32,
                                help_text="Please enter the publisher of the book.",
                                required=False)
    published_date = forms.DateField(label='Published Date:', help_text="Please enter the publish date of the book.",
                                     required=False)
    short_description = forms.Textarea()
    related_url = forms.URLField(label="Related URL",required=False)

    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    downloads = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    upload = forms.FileField(help_text="Click to upload the book.", required=False)
    date_uploaded = forms.DateTimeField(widget=forms.HiddenInput(), required=False)
    date_modified = forms.DateTimeField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Book
        exclude = ('category', 'tag', 'views', 'likes', 'downloads', 'date_uploaded', 'dated_modified',)


class TagForm(forms.ModelForm):
    tag = forms.CharField(label='Add a new tag:', max_length=32,
                            help_text="Please enter the tag name to add a tag.")

    class Meta:
        model = Tag
        fields = ('tag',)

books/views.py
# -*- coding: utf-8 -*-
import os
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from .models import Category, Book, Tag
from .forms import CategoryForm, BookForm, TagForm


def index(request):
    most_download_books = Book.objects.order_by('-downloads')[:5]
    most_liked_books = Book.objects.order_by('-likes')[:5]
    categories = Category.objects.all()

    return render(request, 'books/index.html',
                  {"most_download_books": most_download_books,
                   "most_liked_books": most_liked_books,
                   "categories": categories})


def about(request):
    return render(request, 'books/about.html')


def category_list(request):
    cats = Category.objects.all().order_by('name')
    return render(request, 'books/category_list.html', {"category_list": cats})


def book_list(request):
    books = Book.objects.all().order_by('pk')
    return render(request, 'books/book_list.html', {"book_list": books})


def show_category(request, category_name_slug):
    category = Category.objects.get(slug=category_name_slug)
    books = Book.objects.filter(category=category)
    return render(request, 'books/show_category.html', {'category': category, 'books': books})


@login_required
@permission_required('books.can_edit', raise_exception=True)
def edit_book(request, id):
    book = Book.objects.get(pk=id)
    tags = Tag.objects.filter(book=book)
    try:
        form = BookForm(
            {"title": book.title,
             "author": book.author,
             "publisher": book.publisher,
             "published_date": book.published_date,
             "short_description": book.short_description,
             "related_url": book.related_url,
             "views": book.views,
             "likes": book.likes,
             "downloads": book.downloads,
             "upload": book.upload,
             "date_uploaded": book.date_uploaded,
             "date_modified": book.date_modified}
        )
    except form.DoesNotExist:
        return index(request)

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save(commit=True)
            return render(request, 'books/show_book.html', {'book': book, 'tags': tags})
        else:
            print(form.errors)
    return render(request, 'books/edit_book.html', {'form': form, 'book': book, 'tags': tags})


def show_book(request, id):
    book = Book.objects.get(pk=id)
    tags = Tag.objects.filter(book=book)
    return render(request, 'books/show_book.html', {'book': book, 'tags': tags})


def add_tag(request, id):
    book = Book.objects.get(pk=id)
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=True)
            book.tag.add(tag)
    return redirect('books:show_book', book.id)


def add_book(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = BookForm()
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            if category:
                book = form.save(commit=False)
                book.category = category
                form.save(commit=True)
                tag = Tag.objects.get_or_create(tag=category.slug)[0]
                book.tag.add(tag)
                form.save(commit=True)
                return redirect('books:show_category', category_name_slug)
        else:
            print(form.errors)

    return render(request, 'books/add_book.html', {'form': form})


@login_required
@permission_required('category.can_add', raise_exception=True)
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'books/add_category.html', {'form': form})


@login_required
def download(request, id):
    book = Book.objects.get(pk=id)
    book.downloads += 1
    book.save()
    return redirect('books:serve', book.upload)


def like_book(request):

    book_id = None
    if request.method == 'GET':
        book_id = request.GET['book_id']

    likes = 0
    if book_id:
        book = Book.objects.get(id=int(book_id))

        if book:
            likes = book.likes + 1
            book.likes = likes
            book.save()

    return HttpResponse(likes)


def search(request):
    results = []
    if request.method == 'GET':
        input = request.GET['query']
        query_list = input.split()
        for query in query_list:
            outputs = Book.objects.filter(
                Q(title__icontains=query) | Q(author__icontains=query) | Q(short_description__icontains=query) |
                Q(tag__tag__icontains=query)
            )
            for output in outputs:
                results.append(output)
    results = set(results)
    return render(request, 'books/search_results.html', {'results': results, 'query': input})


def profile(request):
    return render(request, 'books/profile.html')

templates/books/about.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
<h1>About</h1>
<p>This app is created by personal interest, and for test only.</p>
<p>Any questions please contact: <a href="mailto:bifrostx@gmail.com">bifrostx@gmail.com</a></p>
{% endblock %}

templates/books/add_book.html
{% extends 'books/base.html' %}
{% load staticfiles %}
    
{% block body_block %}
    <form role="form" id="book_form" method="post"
          action="." enctype="multipart/form-data">
        <h2>Add a New Book</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="row">
            <div class="col">
                <span style="color:red">{{ form.title.errors }}</span>
                <label class="form-control-label" for="{{ form.title.id_for_label }}">Title:</label>
                <input class="form-control" type="text" name="{{ form.title.html_name }}" required maxlength="128" id="{{ form.title.id_for_label }}" />
            </div>
            <div class="col">
                <span style="color:red">{{ form.author.errors }}</span>
                <label class="form-control-label" for="{{ form.author.id_for_label }}">Author:</label>
                <input class="form-control" type="text" name="{{ form.author.html_name }}" required maxlength="32" id="{{ form.author.id_for_label }}" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <span style="color:red">{{ form.publisher.errors }}</span>
                <label class="form-control-label" for="{{ form.publisher.id_for_label }}">Publisher:</label>
                <input class="form-control" type="text" name="{{ form.publisher.html_name }}" maxlength="32" id="{{ form.publisher.id_for_label }}" />
            </div>
            <div class="col">
                <span style="color:red">{{ form.published_date.errors }}</span>
                <label class="form-control-label" for="{{ form.published_date.id_for_label }}">Published Date:</label>
                <input class="form-control" type="date" name="{{ form.published_date.html_name }}" id="{{ form.published_date.id_for_label }}" />
            </div>
        </div>

        <span style="color:red">{{ form.related_url.errors }}</span>
        <label class="form-control-label" for="{{ form.related_url.id_for_label }}">Related URL:</label>
        <input class="form-control" type="url" name="{{ form.related_url.html_name }}" id="{{ form.related_url.id_for_label }}" />

        <span style="color:red">{{ form.short_description.errors }}</span>
        <label class="form-control-label" for="{{ form.short_description.id_for_label }}">Description:</label>
        <textarea class="form-control" name="{{ form.short_description.html_name }}" rows="10" cols="40" id="{{ form.short_description.id_for_label }}"></textarea><br />

        <span style="color:red">{{ form.upload.errors }}</span>
        <label class="custom-file" for="{{ form.upload.id_for_label }}">Upload:
        {{ form.upload }}<br />

        <!--{% for field in form.visible_fields %}-->
            <!--{{ field.errors }}-->
            <!--{{ field.help_text }}<br />-->
            <!--{{ field.label_tag }}-->
            <!--{{ field }}<br />-->
        <!--{% endfor %}-->
        <br />
        <button type="submit" class="btn btn-primary" name="submit">Add Book</button>
    </form>
{% endblock %}

templates/books/add_category.html
{% extends 'books/base.html' %}
{% load staticfiles %}
    
{% block body_block %}
    <form role="form" id="category_form" method="post"
          action="{% url 'books:add_category' %}">
    <h2>Add Category</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <span style="color:red">{{ form.name.errors }}</span>
        <label class="form-control-label" for="{{ form.name.id_for_label }}">Name of Category</label>
        <input type="text" class="form-control" id="{{ form.name.id_for_label }}"
               name="{{ form.name.html_name }}" placeholder="category" required />
        <!--{% for field in form.visible_fields %}-->
            <!--{{ field.errors }}-->
            <!--{{ field.help_text }}<br />-->
            <!--{{ field }}<br />-->
        <!--{% endfor %}-->
        <br />
        <button type="submit" class="btn btn-primary btn-sm" name="submit">Create Category</button>
    </form>
{% endblock %}

templates/books/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load books_template_tags %}

<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <!-- Custom styles for this template -->
        <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
        <title>My Books</title>
        {% block head_block %}{% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="{% url 'books:index' %}">My Library</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books:index' %}">Home</a>
                    </li>
                    {% get_counts %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'books:profile' %}">{{ user.username }} Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auth_logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration_register' %}">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auth_login' %}">Log in</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books:about' %}">About</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0" method='GET' action="{% url 'books:search' %}">
                    <input class="form-control mr-sm-2" type="text"
                           placeholder="Search" aria-label="Search" name="query">
                    <button id='search' class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">

                <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
                    <h4 class="col-sm-3">Categories</h4>
                    {% block sidebar_block %}
                        {% category_list %}
                        <a class="col-sm-3 text-dark" href="{% url 'books:add_category' %}">Add Category</a>
                    {% endblock %}
                </nav>
                <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
                    {% block body_block %}
                    {% endblock %}
                </main>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="{% static 'js/books-ajax.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    </body>
</html>

templates/books/book_list.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
<h1>All Books</h1>
<table class="table table-hover">
    <thead class="thead-default">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>URL</th>
            <th>Download</th>
        </tr>
    </thead>
    <tbody>
    {% if book_list %}
        {% for b in book_list %}
        <tr>
            <th scope="row">{{ b.id }}</th>
            <td><a href="{% url 'books:show_book' b.id %}">{{ b.title }}</a></td>
            <td>{{ b.author }}</td>
            <td>{{ b.publisher }}</td>
            <td>{{ b.related_url }}</td>
            {% if b.upload %}
            <td><a href="{% url 'books:download' b.id %}">Download</a></td>
            {% else %}
            <td></td>
            {% endif%}
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <th scope="row"></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    {% endif %}
    </tbody>
</table>


{% endblock %}

templates/books/category_list.html
<ul class="nav nav-pills flex-column">
{% if category_list %}
    {% for c in category_list %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'books:show_category' c.slug %}">{{ c.name }}</a>
        </li>
    {% endfor %}
{% else %}
    <li class="nav-item"><a class="nav-link">No category yet.</li>
{% endif %}
</ul>

templates/books/edit_book.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <div>
        <h1>{{ book.title }}</h1>
        <p>{{ book.upload }}</p>

    </div>
    {% if form %}
     <form role="form" id="book_form" method="post" action="{% url 'books:edit_book' book.id %}"
               enctype="multipart/form-data">
        <h2>Edit</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="row">
            <div class="col">
                <span style="color:red">{{ form.title.errors }}</span>
                <label class="form-control-label" for="{{ form.title.id_for_label }}">Title:</label>
                <input class="form-control" type="text" name="{{ form.title.html_name }}" value="{{ form.title.value }}" required maxlength="128" id="{{ form.title.id_for_label }}" />
            </div>
            <div class="col">
                <span style="color:red">{{ form.author.errors }}</span>
                <label class="form-control-label" for="{{ form.author.id_for_label }}">Author:</label>
                <input class="form-control" type="text" name="{{ form.author.html_name }}" value="{{ form.author.value }}" required maxlength="32" id="{{ form.author.id_for_label }}" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <span style="color:red">{{ form.publisher.errors }}</span>
                <label class="form-control-label" for="{{ form.publisher.id_for_label }}">Publisher:</label>
                <input class="form-control" type="text" name="{{ form.publisher.html_name }}" value="{{ form.publisher.value }}" maxlength="32" id="{{ form.publisher.id_for_label }}" />
            </div>
            <div class="col">
                <span style="color:red">{{ form.published_date.errors }}</span>
                <label class="form-control-label" for="{{ form.published_date.id_for_label }}">Published Date:</label>
                <input class="form-control" type="date" name="{{ form.published_date.html_name }}" value="{{ form.published_date.value }}" id="{{ form.published_date.id_for_label }}" />
            </div>
        </div>

        <span style="color:red">{{ form.related_url.errors }}</span>
        <label class="form-control-label" for="{{ form.related_url.id_for_label }}">Related URL:</label>
        <input class="form-control" type="url" name="{{ form.related_url.html_name }}" value="{{ form.related_url.value }}" id="{{ form.related_url.id_for_label }}" />

        <span style="color:red">{{ form.short_description.errors }}</span>
        <label class="form-control-label" for="{{ form.short_description.id_for_label }}">Description:</label>
        <textarea class="form-control" name="{{ form.short_description.html_name }}" rows="10" cols="40" id="{{ form.short_description.id_for_label }}">{{ form.short_description.value }}</textarea><br />

        <span style="color:red">{{ form.upload.errors }}</span>
        <label class="custom-file" for="{{ form.upload.id_for_label }}">Upload:
        {{ form.upload }}<br />

        <!--{% for field in form.visible_fields %}-->
            <!--{{ field.errors }}-->
            <!--{{ field.help_text }}<br />-->
            <!--{{ field.label_tag }}-->
            <!--{{ field }}<br />-->
        <!--{% endfor %}-->
        <br />
        <button type="submit" class="btn btn-primary" name="submit">Finish</button>
     </form>
    {% else %}
        <p>No such book.</p>
    {% endif %}
{% endblock %}

templates/books/get_counts.html
{% if book_num %}
<li class="nav-item"><a class="nav-link" href="{% url 'books:book_list' %}">All Books <span class="badge badge-secondary">{{ book_num }}</span></a></li>
{% endif %}

templates/books/index.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Welcome to the Library.</h1>
    <p class="lead">A place to hold and share books.</p>
</div>
<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Downloaded Books</h4>
        <p>
        {% if most_download_books %}
            {% for book in most_download_books %}
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="{% url 'books:show_book' book.id %}">{{ book.title }} </a>by: {{ book.author }}
                        <span class="badge badge-pill badge-dark">{{ book.downloads }} downloads</span>
                    </li>
                </ul>
            {% endfor %}
        {% else %}
            <strong>No book uploaded yet.</strong>
        {% endif %}
        </p>
    </div>

    <div class="col-lg-6">
        <h4>Most Liked Books</h4>
        <p>
        {% if most_liked_books %}
            {% for book in most_liked_books %}
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="{% url 'books:show_book' book.id %}">{{ book.title }} </a>by: {{ book.author }}
                        <span class="badge badge-pill badge-danger">{{ book.likes }} likes</span>
                    </li>
                </ul>
            {% endfor %}
        {% else %}
            <strong>No book uploaded yet.</strong>
        {% endif %}
        </p>
    </div>
</div>
{% endblock %}

templates/books/profile.html
{% extends "books/base.html" %}
{% load staticfiles %}

{% block body_block %}
    <h1>User Profile</h1>
    {% if user.is_authenticated %}
    <h4>Personal Information</h4>
    <p>
        <span>Username: {{ user.username }}</span><br />
        <span>Email: {{ user.email }}</span>
    </p>
    <h4>Your Permissions</h4>
    <ul>
        {% if perms.category.can_add %}
        <li>Can add new categories.</li>
        {% else %}
        <li>Can not add new category.</li>
        {% endif %}
        {% if perms.books.can_edit %}
        <li>Can edit books.</li>
        {% else %}
        <li>Can not edit books.</li>
        {% endif %}
    </ul>
    <a href="{% url 'auth_password_change' %}">Change password</a>
    {% else %}
        <p>Please log in first.</p>
    {% endif %}
{% endblock %}

templates/books/search_results.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <h1>Search Results</h1>
    {% if results %}
    <h4>Results for <span style="color:red">{{ query }}</span>.</h4>
        {% for b in results %}
        <ul class="list-group">
            <li id="result" class="list-group-item">
                <a href="{% url 'books:show_book' b.id %}">{{ b.title }}</a>
                 by: {{ b.author }}
            </li>
        </ul>
        {% endfor %}
    {% else %}
        <p>No match.</p>
    {% endif %}
{% endblock %}

templates/books/show_book.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <div>
        <h1>{{ book.title }}</h1>

        <p>Tags:
            {% if tags %}
                {% for tag in tags %}
                    <span class="badge badge-pill badge-success">{{ tag }}</span>
                {% endfor %}
            {% endif %}
            <form role="form" id="tag_form" method="post" action="{% url 'books:add_tag' book.id %}">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" name="tag" id="id_tag" required maxlength="32" />
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary" name="submit">Add tag</button>
                </div>
            </div>
            </form>
        </p>
        <strong><span id="like_count">{{ book.likes }}</span> people like this book.</strong>
        <button type="button" id="likes" class="btn btn-danger btn-sm" data-bookid="{{book.id}}">
            like
        </button></h2>
        <hr />
        {% if book.short_description %}
        <div class="jumbotron">
            <h4>Description: </h4>
            <p>{{ book.short_description }}</p>
        </div>
        {% endif %}
            <ul class="list-group">
                <li class="list-group-item">Publisher: {{ book.publisher }}</li>
                <li class="list-group-item">Publish Date: {{ book.published_date }}</li>
                <li class="list-group-item">URL: {{ book.related_url }}</li>
                {% if book.upload %}
                    <li class="list-group-item">Download <a href="{% url 'books:download' book.id %}">{{ book.filename }}</a></li>
                {% else %}
                    <li class="list-group-item">No e-book uploaded yet.</li>
                {% endif %}
            </ul><br />
        <h2><a href="{% url 'books:edit_book' book.id %}"><span class="badge badge-primary">Edit</span></a></h2>
    </div>

{% endblock %}

templates/books/show_category.html
{% extends 'books/base.html' %}
{% load staticfiles %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
    {% else %}
        <p>No such category with that name.</p>
    {% endif %}
    {% if books %}
        {% for book in books %}
        <ul>
            <li><a href="{% url 'books:show_book' book.id %}">{{ book.title }}</a> - by {{ book.author }}</li>
        </ul>
        {% endfor %}
    {% else %}
        <p>No book under this category.</p>
    {% endif %}
    <p><a href="{% url 'books:add_book' category.slug %}">Add New Book</a></p>
{% endblock %}